name: Create Package
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the package to be created'
        required: true
        default: ''
      js:
        description: 'Whether the package requires Javascript'
        required: true
        default: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Creating GitHub Organization Repository
        run: gh repo create --public Snapkg/$REPO --template Snapkg/template
        env:
          REPO: '${{ github.event.inputs.repo-name }}'
          GITHUB_TOKEN: '${{ secrets.ORG_ADMIN_TOKEN }}'
  update-package-manifest:
    name: Updating package manifest.
    uses: Snapkg/workflows/.github/workflows/update-package-manifest.yml@main
    with:
      package: ${{ github.inputs.repo-name }}
      branch: "main"
      manifest: '{"name": "${{github.inputs.repo-name}}"}'
    secrets:
      ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
