# This workflow resyncs modules in the Snapkg/repos repository

name: Sync Repo Submodules

on:
  workflow_dispatch: ~

jobs:
  sync-repo-submodules:
    runs-on: ubuntu/latest
    steps:
      - name: Checkout repository
        run: echo hello world
      #- name: Checkout repository
      #  uses: actions/checkout@v4
      #  with:
      #    repository: 'Snapkg/repos'
      #- name: Checkout submodules
      #  run: git submodule update --init --recursive
      #- name: Update submodules
      #  run: git submodule update --recursive --remote
      #- name: Commit and push changes
      #  uses: stefanzweifel/git-auto-commit-action@v5
      #  with:
      #    commit_message: "Synced submodules"
      
