name: Sync Repo Submodules

on:
  workflow_dispatch: ~

jobs:
  sync-repo-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          repository: 'Snapkg/repos'
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Update submodules
        run: git submodule update --recursive --remote
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Synced submodules"
