# This workflow resyncs modules in the Snapkg/repos repository

name: Sync Repo Submodules

on:
  workflow_dispatch:

jobs:
  sync-repo-submodules:
    runs-on: ubuntu/latest
    name: Syncing Repo Submodules
    
      
