name: Update Package Manifest

on:
  workflow_dispatch:
    inputs:
      package:
        description: "The name of the package to be updated"
        default: "template"
        type: string
        required: true
      branch:
        description: "The name of the branch to be updated"
        default: "main"
        type: string
        required: true
      package-schema:
        description: "The schema version of the manifest"
      package-version:
        description: "The version of the package"
      package-issues:
        description: "The url for the package's issue tracker"
      package-maintainer-github:
        description: "The package maintainers github username"
      package-maintainer-snap:
        description: "The package maintainers Snap! username"
      package-developer-github:
        description: "The package developers github username"
      package-developer-snap:
        description: "The package developers Snap! username"
      package-sources:
        description: "The package's sources (in JSON)"
        
jobs:
  update-package-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Prerequisites
        run: >
          sudo apt-get update &&
          sudo apt-get -y install jq
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          repository: 'Snapkg/${{ github.event.inputs.package }}'
          ref: ${{ github.event.inputs.package-branch }}
      - name: Update manifest.json
        run: >
          ls &&
          jq '.name = "${{ github.event.inputs.package}}"' manifest.json > output.json && mv output.json manifest.json
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated manifest.json"
