name: Update Package Manifest

on:
  workflow_call:
    inputs:
      package:
        description: "The name of the package to be updated"
        default: "template"
        type: string
        required: true
      branch:
        description: "The name of the branch to be updated"
        default: "main"
        type: string
        required: true
      manifest:
        description: "A JSON object containing the properties and values that you'd like to change"
        default: "{}"
        type: string
        required: true
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
        
  workflow_dispatch:
    inputs:
      package:
        description: "The name of the package to be updated"
        default: "template"
        type: string
        required: true
      branch:
        description: "The name of the branch to be updated"
        default: "main"
        type: string
        required: true
      manifest:
        description: "A JSON object containing the properties and values that you'd like to change"
        default: "{}"
        type: string
        required: true
        
jobs:
  update-package-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Prerequisites
        run: >
          sudo apt-get update &&
          sudo apt-get -y install jq
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          repository: 'Snapkg/${{ github.event.inputs.package }}'
          ref: ${{ github.event.inputs.branch }}
      - name: Update manifest.json
        run: >
          ls &&
          jq --argjson update '${{ github.event.inputs.manifest }}' '. + $update' manifest.json  > output.json && mv output.json manifest.json
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated manifest.json"
